config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_param, only: [:edit, :update, :show, :destroy]

  def index
  	@articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def create
  	#render plain: params[:article].inspect
  	@article = Article.new(article_params)
  	if @article.save 
  	  flash[:success] = "Article succesfully created"
  	  redirect_to article_path(@article)
  	else
  	  render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @article.update(article_params)
  	  flash[:success] = "Article succesfully updated"
  	  redirect_to article_path(@article)
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	@article.destroy
  	flash[:danger] = "Article was succesfuly deleted."
  end

  private

  def set_param
    @article = Article.find(params[:id]) 
  end

  def article_params
  	params.require(:article).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<label><%= f.label :title %></label>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :description %><br/>
				</div>
				<div class="col-sm-8">
					<%= f.text_area :description, class: "form-control", placeholder: "Body of article", rows: 10, autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit class: "btn btn-primary btn-lg" %> 
					<%= link_to "Cancel", articles_path, class: "btn btn-danger btn-lg" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/articles/edit.html.erb
<center><h1>Edit Existing Article</h1><br/></center>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="jumbotron">
    <h1>Alpha Blog</h1>
    <p>
      <%= link_to "Signup Now", "#", class: "tn btn-lg btn-primary" %>
<!--       <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
 -->    </p>
  </div>

<% @articles.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 100) %>
			</div>
			<div class="article-actions">
				<%= link_to "Edit Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete Article", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete the article" }, class: "btn btn-xs btn-danger" %>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/new.html.erb
<center><h1>Create an Article</h1></center><br/>

<%= render 'form' %>

app/views/articles/show.html.erb
<center><h2><%= @article.title %></h2></center>

<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center"><strong>Description: </strong></h4>
	<hr>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
		<%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete the article" }, class: "btn btn-xs btn-danger" %>
		<%= link_to "View All", articles_path, class: "btn btn-xs btn-success" %>
	</div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; Jacob Meltzer
		</small>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%= "#{name}" %>">
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" id="logo" href="#">Alpha Blog</a> -->
          <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation' %>
  	<%= render 'layouts/messages' %>
  	<div class="container">
    	<%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title"><%= pluralize(obj.errors.count, "error")%> prohibited this article from being saved:</h2>
				</div>
				<div class="panel-body">
					<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
<% end %>